install.packages("magick")
install.packages("gridExtra")
install.packages("epiDisplay")
install.packages("DT")
install.packages("stargazer")
install.packages("gt")
install.packages("formattable")
install.packages("kableExtra")
install.packages("flextable")
# install.packages("reactablefmtr")
# Archived on 2026-03-17 as issues were not corrected despite reminders. 
install.packages("colorDF")
install.packages("crosstable")
install.packages("tables")
install.packages("xtable")
install.packages("tableone")
# install.packages("rpivotTable")
# Archived on 2026-03-25 as issues were not corrected despite reminders. 
install.packages("GGally")
install.packages("ggsci")
install.packages("blockrand")
install.packages("consort")
install.packages("covadap")
install.packages("reticulate")

# map
install.packages("leaflet")
install.packages("leaflet.extras")
install.packages("tmap")
