# https://thedatasavvycorner.com/blogs/03-quarto-github-actions
# https://www.simonpcouch.com/blog/2020-12-27-r-github-actions-commit/
# https://stackoverflow.com/questions/75791841/github-actions-cant-install-r-package-sf-because-gdal-config-not-found-or-not
# https://r-in-production.org/github-actions.html

name: Render and Publish
on:
  push:
    branches:
      - main  # changes pushed to this branch will trigger a build.

jobs:
  build-deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v3
        - uses: r-lib/actions/setup-r@v2
        - name: Install packages
          run: |
            R -e 'install.packages("rmarkdown")'
            R -e 'install.packages("magick")'
            R -e 'install.packages("gridExtra")'
            R -e 'install.packages("epiDisplay")'
            R -e 'install.packages("DT")'
            R -e 'install.packages("stargazer")'
            R -e 'install.packages("gt")'
            R -e 'install.packages("formattable")'
            R -e 'install.packages("kableExtra")'
            R -e 'install.packages("flextable")'
            R -e 'install.packages("reactablefmtr")'
            R -e 'install.packages("colorDF")'
            R -e 'install.packages("crosstable")'
            R -e 'install.packages("tables")'
            R -e 'install.packages("tableone")'
            R -e 'install.packages("rpivotTable")'
            R -e 'install.packages("GGally")'
            R -e 'install.packages("ggsci")'
            R -e 'install.packages("blockrand")'
            R -e 'install.packages("consort")'
            R -e 'install.packages("covadap")'
            R -e 'install.packages("reticulate")'
            
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            version: 1.3.340

        - name: Publish to GitHub Pages (and render)
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: gh-pages # renderred html files will be pushed here
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}